### ISSUE TITLE
Missing Voronoi edges

### ISSUE THREAD

**Issue by robertdj** [JuliaGeometry/VoronoiDelaunay.jl#14]
When plotting edges as illustrated in the README, the Delaunay edges all show up as expected, but I often find Voronoi edges missing. 
(`collect`ing the Voronoi edges also reveal that only a subset of the edges are available)

Consider e.g. the following code:

```julia
using VoronoiDelaunay

N = 8
pts = Point2D[]
for n = 1:N
	x = 1 + rand()
	y = 1 + rand()
	push!(pts, Point2D(x,y))
end

tess = DelaunayTessellation(N)
push!(tess, pts)

using Winston

Vx, Vy = getplotxy(voronoiedges(tess))
plot(Vx, Vy)

Dx, Dy = getplotxy(delaunayedges(tess))
oplot(Dx, Dy, "r--")
```

One realization looks as follows (black lines = Voronoi; red lines = Delaunay; stars = points from `pts`):
![voronoi](https://cloud.githubusercontent.com/assets/5703657/12307976/f57175c6-ba42-11e5-917d-61aa4c55eea2.png)

**Comment by skariel** [comment]
yes, its a bug which I fixed locally. Let me fix this here in a few minutes...

**Comment by skariel** [comment]
fixed now in master, please try and tell me if it works for you

**Comment by skariel** [comment]
well... not completely fixed. Fixing some more now...

**Comment by skariel** [comment]
ok, fixed now note it will iterate over the point at the corners of the allowed area too (1,1 1,2 2,1 22)

it looks just fine now:

![index](https://cloud.githubusercontent.com/assets/2347816/12323587/5da69a40-bac5-11e5-9d2a-dc2ceb027cbe.png)

**Comment by robertdj** [comment]
Great -- thanks!
