### ISSUE TITLE
Fix indentation in the source

### ISSUE THREAD

**Issue by juliohm** [JuliaGeometry/VoronoiDelaunay.jl#28]
The source code has mixed indentation, it shows up completely misaligned in my text editor.

Please consider removing all tabs and using spaces only: http://softwareengineering.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e

**Comment by juliohm** [comment]
Can I send a PR?

**Comment by skariel** [comment]
please send a PR, I prefer 4 spaces.   Thanks!
