### ISSUE TITLE
New releases are needed for v0.6

### ISSUE THREAD

**Issue by robertdj** [JuliaGeometry/VoronoiDelaunay.jl#32]
Both GeometricalPredicates and VoronoiDelaunay works without warnings with Julia v0.6 **on the latest version of their master branch**.
I think new releases should be made that drop support for anything below v0.6 as there are breaking changes (this will also fix the "build failing" Travis flag :-)).

My question is: What should we bump -- `:patch`, `:minor` or `:major`? I'm leaning towards `:minor`.

**Comment by robertdj** [comment]
@skariel

**Comment by skariel** [comment]
@robertdj great! lets bump minor
