### ISSUE TITLE
1.0 compatibility

### ISSUE THREAD

**Issue by mkborregaard** [JuliaGeometry/VoronoiDelaunay.jl#45]
This seems to be one of the packages that have been automatically capped to julia 0.6. Are you planning to issue a 1.0-compatible release soonish? I see that there's active updating going on to that effect :-)

**Comment by skariel** [comment]
I can use it fine with Julia v1.0.0, just tested. Only a couple of warning when `using` but otherwise all good...

**Comment by mkborregaard** [comment]
Awesome, then it's possible just a case of pushing a release (it won't install because of the auto-cap).

**Comment by mkborregaard** [comment]
I did, thank you!
