### ISSUE TITLE
Native 32 bit support

### ISSUE THREAD

**Issue by sjkelly** [JuliaGeometry/VoronoiDelaunay.jl#62]
xref: https://github.com/JuliaGeometry/GeometricalPredicates.jl/issues/43

We have GeometricalPreciates now working on `x86`, so it may be good to support 32 bit here as well.

**Comment by dkarrasch** [comment]
There seems to be not a single occurence of `Int`, there's only `Int64`. Let's open a branch, add CI and see what happens.
